In [35]:
import pandas as pd

In [36]:
import matplotlib.pyplot as plt

Project 1: Compare 2 entities to one another and base the comparison on 1 factor they both share. In this assignment I've compared 2 high schools and the number of students (min & max) that took Regents Exams from 2014 - 2017. I chose High Schools in this case because they're known for taking regents exams.

In [37]:
df=pd.read_csv("https://raw.githubusercontent.com/CunyLaguardiaDataAnalytics/datasets/master/2014-15_To_2016-17_School-_Level_NYC_Regents_Report_For_All_Variables.csv")

Step 1: establish how many rows and columns in the data set

In [38]:
df.shape

(212331, 15)

Step 2: Get a visual of Columns in spread sheet format to get a better feel of the data

In [39]:
df

,School DBN,School Name,School Level,Regents Exam,Year,Total Tested,Mean Score,Number Scoring Below 65,Percent Scoring Below 65,Number Scoring 65 or Above,Percent Scoring 65 or Above,Number Scoring 80 or Above,Percent Scoring 80 or Above,Number Scoring CR,Percent Scoring CR
0,01M034,P.S. 034 Franklin D. Roosevelt,K-8,Common Core Algebra,2017,4,s,s,s,s,s,s,s,na,na
1,01M034,P.S. 034 Franklin D. Roosevelt,K-8,Living Environment,2015,16,77.9,1,6.3,15,93.8,7,43.8,na,na
2,01M034,P.S. 034 Franklin D. Roosevelt,K-8,Living Environment,2016,9,74,1,11.1,8,88.9,2,22.2,na,na
3,01M140,P.S. 140 Nathan Straus,K-8,Common Core Algebra,2016,3,s,s,s,s,s,s,s,na,na
4,01M140,P.S. 140 Nathan Straus,K-8,Common Core Algebra,2017,2,s,s,s,s,s,s,s,na,na
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212326,84X717,Icahn Charter School,K-8,Living Environment,2016,8,s,s,s,s,s,s,s,na,na
212327,84X717,Icahn Charter School,K-8,Living Environment,2016,5,s,s,s,s,s,s,s,na,na
212328,84X717,Icahn Charter School,K-8,Living Environment,2017,6,s,s,s,s,s,s,s,na,na
212329,84X717,Icahn Charter School,K-8,Living Environment,2017,4,s,s,s,s,s,s,s,na,na
212330,84X717,Icahn Charter School,K-8,U.S. History and Government,2015,1,s,s,s,s,s,s,s,na,na

Step 2: display a list of Columns making them accessible for copy and paste

In [40]:
df.columns

Index(['School DBN', 'School Name', 'School Level', 'Regents Exam', 'Year',
       'Total Tested', 'Mean Score', 'Number Scoring Below 65',
       'Percent Scoring Below 65', 'Number Scoring 65 or Above',
       'Percent Scoring 65 or Above', 'Number Scoring 80 or Above',
       'Percent Scoring 80 or Above', 'Number Scoring CR',
       'Percent Scoring CR'],
      dtype='object')

Step 3: create a subset of the information neccessary to simplify the task.

In [41]:
df2 = df[['School Name', 'School Level', 'Regents Exam', 'Total Tested']]
df2

,School Name,School Level,Regents Exam,Total Tested
0,P.S. 034 Franklin D. Roosevelt,K-8,Common Core Algebra,4
1,P.S. 034 Franklin D. Roosevelt,K-8,Living Environment,16
2,P.S. 034 Franklin D. Roosevelt,K-8,Living Environment,9
3,P.S. 140 Nathan Straus,K-8,Common Core Algebra,3
4,P.S. 140 Nathan Straus,K-8,Common Core Algebra,2
...,...,...,...,...
212326,Icahn Charter School,K-8,Living Environment,8
212327,Icahn Charter School,K-8,Living Environment,5
212328,Icahn Charter School,K-8,Living Environment,6
212329,Icahn Charter School,K-8,Living Environment,4
212330,Icahn Charter School,K-8,U.S. History and Government,1

Step 4: Display High Schools Only

In [42]:
high_schools = df[df['School Level'].str.contains('High School', case=False, na=False)][['School Name', 'School Level']]
high_schools

                                 School Name School Level
18                Orchard Collegiate Academy  High school
19                Orchard Collegiate Academy  High school
20                Orchard Collegiate Academy  High school
21                Orchard Collegiate Academy  High school
22                Orchard Collegiate Academy  High school
...                                      ...          ...
212096  South Bronx Community Charter School  High school
212097  South Bronx Community Charter School  High school
212098  South Bronx Community Charter School  High school
212099  South Bronx Community Charter School  High school
212100  South Bronx Community Charter School  High school

[151160 rows x 2 columns]

Step 5: Change total tested to numeric so a total of students tested can be accurately computed.

In [43]:
high_schools_data = df[df['School Level'].str.contains('High School', case=False, na=False)].copy()
high_schools_data['Total Tested'] = pd.to_numeric(high_schools_data['Total Tested'], errors='coerce')
high_schools_data2 = high_schools_data[['School Name', 'School Level', 'Total Tested']]

Step 5: Use the groupby function to get counting the total tested and perform a maximum and minumum count to distinguish the 2 high schools with the greatest and least amount of students to take regents exams

In [44]:
high_schools = df[df['School Level'].str.contains('High School', case=False, na=False)].copy()
high_schools['Total Tested'] = pd.to_numeric(high_schools_data['Total Tested'], errors='coerce')
regents_exams_counts = high_schools_data.groupby('School Name')['Total Tested'].sum()
most_exams_school = regents_exams_counts.idxmax()
least_exams_school = regents_exams_counts.idxmin()
most_exams_count = regents_exams_counts.max()
least_exams_count = regents_exams_counts.min()
print(f"The high school that took the greatest amount of Regents exams is {most_exams_school} with {most_exams_count} exams.")
print(f"The high school that took the least amount of Regents exams is {least_exams_school} with {least_exams_count} exams.")

The high school that took the greatest amount of Regents exams is Brooklyn Technical High School with 178560 exams.
The high school that took the least amount of Regents exams is International Arts Business School with 85 exams.